import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 👇 Your AdSense meta tag goes here 👇 */}
        <meta
          name="google-adsense-account"
          content="ca-pub-8621118119905256"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
